let randomNumber = Math.floor(Math.random() * 100 + 1);
let chances = 0;
let guess;

console.log(
  "This is a guessing game and you have to enter a number and if it matches with the number generated by computer, then you win...\n"
);

guess = prompt("Enter a Number Between 1 to 100");
++chances;

do {
  guess = Number.parseInt(guess);

  if (guess > randomNumber) {
    console.log("Number Entered is Greater");
    guess = prompt("Try Again :");
    guess = Number.parseInt(guess);
    ++chances;
    continue;
  } else if (guess < randomNumber) {
    console.log("Number Entered is Smaller");
    guess = prompt("Try Again :");
    guess = Number.parseInt(guess);
    ++chances;
    continue;
  }
} while (guess != randomNumber);

let score = 100 - chances;
console.log(
  "\nCongratulations🥳🥳\nThe number generated was",
  randomNumber + " and you guessed it right😁\nYour final score is",
  score
);
